In [2]:
##importing pandas

import pandas as pd

In [3]:
##building my df 
data = pd.read_csv("copper-duty_annual.csv")

In [5]:
##is this as ugly as i think it is ?
data.shape

(8, 1)

In [23]:
##answer yes, lets clean this mofo 
data=data.reset_index()

In [24]:
## transposing the data 
np_array = data.to_numpy().T
copper = pd.DataFrame(np_array, index=data.columns, columns=data.index)

In [27]:
## resetting the column heads and cleaning the index 
copper.columns = copper.iloc[0]

# resetting the index and cleaning 
copper = copper.drop(copper.index[0])
copper = copper.reset_index(drop=True)

In [29]:
copper.tail(10)

level_0,Commodity,Country,CountrySubCode,RateProvision,District,Time,Measures,Calculated Duty($US)
156,7419801600 Copper Springs (kg),World Total,All Country Subcodes,All Rate Provisions,All Districts,2025,NaN,201650
157,7419801600 Copper Springs (kg),World Total,All Country Subcodes,All Rate Provisions,All Districts,2026 through August,NaN,207268
158,7419801700 Copper Chain And Parts Thereof (kg),World Total,All Country Subcodes,All Rate Provisions,All Districts,2025,NaN,799530
159,7419801700 Copper Chain And Parts Thereof (kg),World Total,All Country Subcodes,All Rate Provisions,All Districts,2026 through August,NaN,787411
160,7419803000 Artcls O Cppr Nesoi Ctd Or Pltd W P...,World Total,All Country Subcodes,All Rate Provisions,All Districts,2025,NaN,2275948
161,7419803000 Artcls O Cppr Nesoi Ctd Or Pltd W P...,World Total,All Country Subcodes,All Rate Provisions,All Districts,2026 through August,NaN,3400526
162,7419805010 Brass Plumbing Goods Nesoi (kg),World Total,All Country Subcodes,All Rate Provisions,All Districts,2025,NaN,36050185
163,7419805010 Brass Plumbing Goods Nesoi (kg),World Total,All Country Subcodes,All Rate Provisions,All Districts,2026 through August,NaN,35149150
164,"7419805050 Other Articles Of Copper, Nesoi (kg)",World Total,All Country Subcodes,All Rate Provisions,All Districts,2025,NaN,51033046
165,"7419805050 Other Articles Of Copper, Nesoi (kg)",World Total,All Country Subcodes,All Rate Provisions,All Districts,2026 through August,NaN,60999682

In [38]:
copper[['HTS Code', 'Product Name']] = copper['Commodity'].str.split(' ',n=1, expand=True)

In [39]:
copper.head(10)

level_0,Commodity,Country,CountrySubCode,RateProvision,District,Time,Measures,Calculated Duty($US),HTS Code,Product Name
0,740610 Copper Powders Of Non-lamellar Structure,World Total,All Country Subcodes,All Rate Provisions,All Districts,2025,NaN,5537331,740610,Copper Powders Of Non-lamellar Structure
1,740610 Copper Powders Of Non-lamellar Structure,World Total,All Country Subcodes,All Rate Provisions,All Districts,2026 through August,NaN,16029458,740610,Copper Powders Of Non-lamellar Structure
2,740620 Copper Powders Of Lamellar Structure; F...,World Total,All Country Subcodes,All Rate Provisions,All Districts,2025,NaN,897029,740620,Copper Powders Of Lamellar Structure; Flakes
3,740620 Copper Powders Of Lamellar Structure; F...,World Total,All Country Subcodes,All Rate Provisions,All Districts,2026 through August,NaN,3078653,740620,Copper Powders Of Lamellar Structure; Flakes
4,7407101500 Hollow Profiles Of Refined Copper (kg),World Total,All Country Subcodes,All Rate Provisions,All Districts,2025,NaN,5661809,7407101500,Hollow Profiles Of Refined Copper (kg)
5,7407101500 Hollow Profiles Of Refined Copper (kg),World Total,All Country Subcodes,All Rate Provisions,All Districts,2026 through August,NaN,23830349,7407101500,Hollow Profiles Of Refined Copper (kg)
6,7407103000 Profiles Of Refined Copper Not Holl...,World Total,All Country Subcodes,All Rate Provisions,All Districts,2025,NaN,12175444,7407103000,Profiles Of Refined Copper Not Hollow Profiles...
7,7407103000 Profiles Of Refined Copper Not Holl...,World Total,All Country Subcodes,All Rate Provisions,All Districts,2026 through August,NaN,17226325,7407103000,Profiles Of Refined Copper Not Hollow Profiles...
8,7407105010 Bars A Rds Ref Cppr Hvg A Rctnglr C...,World Total,All Country Subcodes,All Rate Provisions,All Districts,2025,NaN,22227164,7407105010,Bars A Rds Ref Cppr Hvg A Rctnglr Crss Sctn (kg)
9,7407105010 Bars A Rds Ref Cppr Hvg A Rctnglr C...,World Total,All Country Subcodes,All Rate Provisions,All Districts,2026 through August,NaN,29222919,7407105010,Bars A Rds Ref Cppr Hvg A Rctnglr Crss Sctn (kg)

In [40]:
copper.to_csv("export-copper-duty-annual.csv", index=False)